language: scala
scala:
  - 2.12.7
jdk: oraclejdk8

services:
  - docker

install: true

script:
  - travis_wait ./check_build.sh

deploy:
    provider: script
    script: cd /tmp/spark/resource-managers/pbs && sh dev/deploy_docker.sh
    #on:
        #branch: master
