language: scala
scala:
  - 2.12.7
jdk: oraclejdk8

services:
  - docker

install: true

script:
  - travis_wait ./check_build.sh

deploy:
    skip_cleanup: true
    provider: script
    script: cd /tmp/spark/resource-managers/pbs && ./dev/deploy_docker.sh
    on:
        branch: deploy_docker_test2
