language: scala
scala:
  - 2.12.7
jdk: oraclejdk8

branches:
  only:
    - master

install: true

script:
  - travis_wait ./check_build.sh

deploy:
    provider: script
    script: bash cd /tmp/spark/resource-managers/pbs && dev/deploy_docker.sh
    on:
        branch: master
